<a href="https://colab.research.google.com/github/charlottesscott/Breast_Screening_Uptake_Prediction/blob/main/01_Data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import Python Libraries**

Pandas - allows work with tables

Numpy - used for calculations

In [1]:
import pandas as pd
import numpy as np

**Upload CSVs**

File picker appears

In [3]:
from google.colab import files

uploaded = files.upload()

Saving kc62_cancers_detected_24-25.csv to kc62_cancers_detected_24-25.csv
Saving kc62_diagnostic_outcomes_24-25.csv to kc62_diagnostic_outcomes_24-25.csv
Saving kc62_invite_screened_uptake_24-25.csv to kc62_invite_screened_uptake_24-25.csv
Saving kc62_referral_outcome_24-25.csv to kc62_referral_outcome_24-25.csv
Saving kc63_coverage_24-25.csv to kc63_coverage_24-25 (1).csv

**Read files**

In [4]:
uptake = pd.read_csv("kc62_invite_screened_uptake_24-25.csv")
coverage = pd.read_csv("kc63_coverage_24-25.csv")
cancers = pd.read_csv("kc62_cancers_detected_24-25.csv")
diagnostic = pd.read_csv("kc62_diagnostic_outcomes_24-25.csv")
referral = pd.read_csv("kc62_referral_outcome_24-25.csv")

**Explore Each Dataset**

In [5]:
uptake.head()

,CollectionYearRange,Parent_Org_Code,Parent_Org_Name,Org_Name,Org_Type,Age_Band,Table_Code,Screened,Invited,Uptake
0,2014-15,E92000001,England,England,National,45-49,A,159030.0,238589.0,66.65437216300836
1,2014-15,E92000001,England,England,National,45-49,A and C1,170563.0,252740.0,67.48555828123763
2,2014-15,E92000001,England,England,National,45-49,A to C2,172930.0,259507.0,66.63789416085115
3,2014-15,E92000001,England,England,National,45-49,A to D,173032.0,259609.0,66.6510020839031
4,2014-15,E92000001,England,England,National,45-49,B,1971.0,6151.0,32.04357015119493

In [6]:
uptake.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8593 entries, 0 to 8592
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CollectionYearRange  8593 non-null   object
 1   Parent_Org_Code      8593 non-null   object
 2   Parent_Org_Name      8593 non-null   object
 3   Org_Name             8593 non-null   object
 4   Org_Type             8593 non-null   object
 5   Age_Band             8593 non-null   object
 6   Table_Code           8593 non-null   object
 7   Screened             8593 non-null   object
 8   Invited              8593 non-null   object
 9   Uptake               8593 non-null   object
dtypes: object(10)
memory usage: 671.5+ KB

In [7]:
uptake.columns

Index(['CollectionYearRange', 'Parent_Org_Code', 'Parent_Org_Name', 'Org_Name',
       'Org_Type', 'Age_Band', 'Table_Code', 'Screened', 'Invited', 'Uptake'],
      dtype='object')

In [8]:
uptake.isna().sum()

CollectionYearRange    0
Parent_Org_Code        0
Parent_Org_Name        0
Org_Name               0
Org_Type               0
Age_Band               0
Table_Code             0
Screened               0
Invited                0
Uptake                 0
dtype: int64

In [9]:
coverage.head()

,CollectionYearRange,Parent_OrgONSCode,Parent_Org_Name,Org_ONSCode,Org_Name,Org_Type,Age_Band,Women_resident,Women_ineligible,Women_eligible,Women_never_screened,Percent_never_screened,Women_screened_less3yrs,Coverage
0,2014-15,E92000001,England,E92000001,England,National,45-49,2021433,573,2020860,1768799,87.52704294,251042,12.422533
1,2014-15,E92000001,England,E92000001,England,National,50,409486,352,409134,226553,55.37378952,178826,43.708418
2,2014-15,E92000001,England,E92000001,England,National,51-52,793873,862,793011,276121,34.81931524,502582,63.376422
3,2014-15,E92000001,England,E92000001,England,National,53-54,749463,991,748472,153854,20.55574557,551576,73.693605
4,2014-15,E92000001,England,E92000001,England,National,53<71,5750911,9928,5740983,670738,11.68333019,4329310,75.410605

In [10]:
coverage.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1879 entries, 0 to 1878
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   CollectionYearRange      1879 non-null   object
 1   Parent_OrgONSCode        1879 non-null   object
 2   Parent_Org_Name          1879 non-null   object
 3   Org_ONSCode              1879 non-null   object
 4   Org_Name                 1879 non-null   object
 5   Org_Type                 1879 non-null   object
 6   Age_Band                 1879 non-null   object
 7   Women_resident           1879 non-null   object
 8   Women_ineligible         1879 non-null   object
 9   Women_eligible           1879 non-null   int64
 10  Women_never_screened     1879 non-null   object
 11  Percent_never_screened   1879 non-null   object
 12  Women_screened_less3yrs  1879 non-null   int64
 13  Coverage                 1879 non-null   float64
dtypes: float64(1), int64(2), object(11)
memory usage: 205.6+ KB

In [11]:
coverage.columns

Index(['CollectionYearRange', 'Parent_OrgONSCode', 'Parent_Org_Name',
       'Org_ONSCode', 'Org_Name', 'Org_Type', 'Age_Band', 'Women_resident',
       'Women_ineligible', 'Women_eligible', 'Women_never_screened',
       'Percent_never_screened', 'Women_screened_less3yrs', 'Coverage'],
      dtype='object')

In [12]:
coverage.isna().sum()

CollectionYearRange        0
Parent_OrgONSCode          0
Parent_Org_Name            0
Org_ONSCode                0
Org_Name                   0
Org_Type                   0
Age_Band                   0
Women_resident             0
Women_ineligible           0
Women_eligible             0
Women_never_screened       0
Percent_never_screened     0
Women_screened_less3yrs    0
Coverage                   0
dtype: int64

In [13]:
cancers.head()

,CollectionYearRange,Parent_Org_Code,Parent_Org_Name,Org_Name,Org_Type,Age_Band,Table_Code,Total_with_cancer,Invasive_total,Non_or_micro_invasive,...,Invasive_lessthan10mm,Invasive_10mmto15mm,Invasive_15mmto20mm,Invasive_20mmto50mm,Invasive_50mmplus,Invasive_unknown,Rate_with_cancer,Rate_non_or_micro_invasive,Rate_small_invasive,Percent_small_invasive
0,2014-15,E92000001,England,England,National,45 and over,A,2597.0,1843.0,751.0,...,422.0,435.0,348.0,501.0,62.0,75.0,7.626011246678119,2.2052885815384164,2.516554346708952,46.500271296798694
1,2014-15,E92000001,England,England,National,45 and over,A to F2,18015.0,14089.0,3907.0,...,3559.0,3742.0,2680.0,3285.0,339.0,484.0,8.556349366929886,1.8556567847124659,3.467660656561483,51.82056923841295
2,2014-15,E92000001,England,England,National,45 and over,B,644.0,497.0,146.0,...,102.0,116.0,97.0,134.0,27.0,21.0,10.879664825232712,2.466507864105553,3.6828679066781547,43.86317907444668
3,2014-15,E92000001,England,England,National,45 and over,C1,11642.0,9214.0,2417.0,...,2424.0,2529.0,1767.0,2030.0,190.0,274.0,7.932771093696235,1.646925591261278,3.374936886022801,53.75515519861081
4,2014-15,E92000001,England,England,National,45 and over,C2,1413.0,1131.0,280.0,...,282.0,293.0,204.0,269.0,38.0,45.0,12.156093532235586,2.408850806104716,4.9467471911078995,50.83996463306808

In [14]:
cancers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2866 entries, 0 to 2865
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   CollectionYearRange         2866 non-null   object
 1   Parent_Org_Code             2866 non-null   object
 2   Parent_Org_Name             2866 non-null   object
 3   Org_Name                    2866 non-null   object
 4   Org_Type                    2866 non-null   object
 5   Age_Band                    2866 non-null   object
 6   Table_Code                  2866 non-null   object
 7   Total_with_cancer           2866 non-null   float64
 8   Invasive_total              2866 non-null   object
 9   Non_or_micro_invasive       2866 non-null   object
 10  Cancer_non_microinvasive    2866 non-null   object
 11  Cancer_microinvasive        2866 non-null   object
 12  Small_invasive              2866 non-null   object
 13  Invasive_not_known          2866 non-null   object
 14  Invasive_lessthan10mm       2866 non-null   object
 15  Invasive_10mmto15mm         2866 non-null   object
 16  Invasive_15mmto20mm         2866 non-null   object
 17  Invasive_20mmto50mm         2866 non-null   object
 18  Invasive_50mmplus           2866 non-null   object
 19  Invasive_unknown            2866 non-null   object
 20  Rate_with_cancer            2866 non-null   object
 21  Rate_non_or_micro_invasive  2866 non-null   object
 22  Rate_small_invasive         2866 non-null   object
 23  Percent_small_invasive      2866 non-null   object
dtypes: float64(1), object(23)
memory usage: 537.5+ KB

In [15]:
cancers.columns

Index(['CollectionYearRange', 'Parent_Org_Code', 'Parent_Org_Name', 'Org_Name',
       'Org_Type', 'Age_Band', 'Table_Code', 'Total_with_cancer',
       'Invasive_total', 'Non_or_micro_invasive', 'Cancer_non_microinvasive',
       'Cancer_microinvasive', 'Small_invasive', 'Invasive_not_known',
       'Invasive_lessthan10mm', 'Invasive_10mmto15mm', 'Invasive_15mmto20mm',
       'Invasive_20mmto50mm', 'Invasive_50mmplus', 'Invasive_unknown',
       'Rate_with_cancer', 'Rate_non_or_micro_invasive', 'Rate_small_invasive',
       'Percent_small_invasive'],
      dtype='object')

In [16]:
cancers.isna().sum()

CollectionYearRange           0
Parent_Org_Code               0
Parent_Org_Name               0
Org_Name                      0
Org_Type                      0
Age_Band                      0
Table_Code                    0
Total_with_cancer             0
Invasive_total                0
Non_or_micro_invasive         0
Cancer_non_microinvasive      0
Cancer_microinvasive          0
Small_invasive                0
Invasive_not_known            0
Invasive_lessthan10mm         0
Invasive_10mmto15mm           0
Invasive_15mmto20mm           0
Invasive_20mmto50mm           0
Invasive_50mmplus             0
Invasive_unknown              0
Rate_with_cancer              0
Rate_non_or_micro_invasive    0
Rate_small_invasive           0
Percent_small_invasive        0
dtype: int64

In [17]:
diagnostic.head()

,CollectionYearRange,Parent_Org_Code,Parent_Org_Name,Org_Name,Org_Type,Age_Band,Table_Code,Rate_benign_biopsy,Rate_benign_biopsy_warning,Non-op_diag_rate_invasive,Non-op_diag_rate_non-invasive,Rate_non_op_diagnosis,Rate_non_op_diagnosis_warning,Rate_small_invasive,Rate_small_invasive_warning,SDR,SDR_warning
0,2014-15,E92000001,England,England,National,50<71,A to F2,0.524701,NaN,:,:,97.325089,NaN,not included,not included,not included,not included
1,2015-16,E92000001,England,England,National,50<71,A to F2,0.463810,NaN,:,:,97.505294,NaN,not included,not included,not included,not included
2,2016-17,E92000001,England,England,National,50<71,A to F2,0.402010,NaN,:,:,97.845932,NaN,not included,not included,not included,not included
3,2017-18,E92000001,England,England,National,50<71,A to F2,0.360965,NaN,:,:,98.007514,NaN,not included,not included,not included,not included
4,2018-19,E92000001,England,England,National,50<71,A to F2,0.304110,NaN,:,:,98.246647,NaN,not included,not included,not included,not included

In [18]:
diagnostic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2847 entries, 0 to 2846
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   CollectionYearRange            2847 non-null   object
 1   Parent_Org_Code                2847 non-null   object
 2   Parent_Org_Name                2847 non-null   object
 3   Org_Name                       2847 non-null   object
 4   Org_Type                       2847 non-null   object
 5   Age_Band                       2847 non-null   object
 6   Table_Code                     2847 non-null   object
 7   Rate_benign_biopsy             2847 non-null   float64
 8   Rate_benign_biopsy_warning     2596 non-null   object
 9   Non-op_diag_rate_invasive      2847 non-null   object
 10  Non-op_diag_rate_non-invasive  2847 non-null   object
 11  Rate_non_op_diagnosis          2847 non-null   float64
 12  Rate_non_op_diagnosis_warning  505 non-null    object
 13  Rate_small_invasive            2847 non-null   object
 14  Rate_small_invasive_warning    1846 non-null   object
 15  SDR                            2847 non-null   object
 16  SDR_warning                    1579 non-null   object
dtypes: float64(2), object(15)
memory usage: 378.2+ KB

In [19]:
diagnostic.columns

Index(['CollectionYearRange', 'Parent_Org_Code', 'Parent_Org_Name', 'Org_Name',
       'Org_Type', 'Age_Band', 'Table_Code', 'Rate_benign_biopsy',
       'Rate_benign_biopsy_warning', 'Non-op_diag_rate_invasive',
       'Non-op_diag_rate_non-invasive', 'Rate_non_op_diagnosis',
       'Rate_non_op_diagnosis_warning', 'Rate_small_invasive',
       'Rate_small_invasive_warning', 'SDR', 'SDR_warning'],
      dtype='object')

In [20]:
diagnostic.isna().sum()

CollectionYearRange                 0
Parent_Org_Code                     0
Parent_Org_Name                     0
Org_Name                            0
Org_Type                            0
Age_Band                            0
Table_Code                          0
Rate_benign_biopsy                  0
Rate_benign_biopsy_warning        251
Non-op_diag_rate_invasive           0
Non-op_diag_rate_non-invasive       0
Rate_non_op_diagnosis               0
Rate_non_op_diagnosis_warning    2342
Rate_small_invasive                 0
Rate_small_invasive_warning      1001
SDR                                 0
SDR_warning                      1268
dtype: int64

In [21]:
referral.head()

,CollectionYearRange,Parent_Org_Code,Parent_Org_Name,Org_Name,Org_Type,Age_Band,Table_Code,Initial_referred,Percent_assessment,Referral_cyt_bio,Open_biop_total,Final_STR,Percent_STR
0,2014-15,E92000001,England,England,National,45 and over,A,26401.0,7.752573081384252,11970.0,670.0,263.0,0.07722914739608568
1,2014-15,E92000001,England,England,National,45 and over,A to F2,87737.0,4.167129749688191,40509.0,1770.0,931.0,0.044218491593737023
2,2014-15,E92000001,England,England,National,45 and over,B,4688.0,7.919855388306049,2291.0,115.0,68.0,0.11487844846519014
3,2014-15,E92000001,England,England,National,45 and over,C1,44144.0,3.007938903625894,20272.0,770.0,409.0,0.027868951875294277
4,2014-15,E92000001,England,England,National,45 and over,C2,5560.0,4.783289457836508,2790.0,91.0,61.0,0.052478535418709886

In [22]:
referral.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2866 entries, 0 to 2865
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CollectionYearRange  2866 non-null   object
 1   Parent_Org_Code      2866 non-null   object
 2   Parent_Org_Name      2866 non-null   object
 3   Org_Name             2866 non-null   object
 4   Org_Type             2866 non-null   object
 5   Age_Band             2866 non-null   object
 6   Table_Code           2866 non-null   object
 7   Initial_referred     2866 non-null   object
 8   Percent_assessment   2866 non-null   object
 9   Referral_cyt_bio     2866 non-null   object
 10  Open_biop_total      2866 non-null   object
 11  Final_STR            2866 non-null   object
 12  Percent_STR          2866 non-null   object
dtypes: object(13)
memory usage: 291.2+ KB

In [23]:
referral.columns

Index(['CollectionYearRange', 'Parent_Org_Code', 'Parent_Org_Name', 'Org_Name',
       'Org_Type', 'Age_Band', 'Table_Code', 'Initial_referred',
       'Percent_assessment', 'Referral_cyt_bio', 'Open_biop_total',
       'Final_STR', 'Percent_STR'],
      dtype='object')

In [24]:
referral.isna().sum()

CollectionYearRange    0
Parent_Org_Code        0
Parent_Org_Name        0
Org_Name               0
Org_Type               0
Age_Band               0
Table_Code             0
Initial_referred       0
Percent_assessment     0
Referral_cyt_bio       0
Open_biop_total        0
Final_STR              0
Percent_STR            0
dtype: int64

**Standardise Column Names**

In [25]:
def clean_columns(df):
    df.columns = (
        df.columns
        .str.lower()
        .str.strip()
        .str.replace(" ", "_")
        .str.replace(r"[^\w]", "", regex=True)
    )
    return df

In [26]:
uptake = clean_columns(uptake)
coverage = clean_columns(coverage)
cancers = clean_columns(cancers)
diagnostic = clean_columns(diagnostic)
referral = clean_columns(referral)

**Joining Keys**

In [29]:
kc62_key = [
    "collectionyearrange",
    "parent_org_code",
    "org_name",
    "org_type",
    "age_band",
    "table_code"
]

In [35]:
kc62_key = [
    "collectionyearrange",
    "parent_org_code", "parent_org_name",
    "org_name",
    "org_type",
    "age_band",
    "table_code"
]

for name, df in {
    "cancers": cancers,
    "diagnostic": diagnostic,
    "uptake": uptake,
    "referral": referral
}.items():

    duplicate_count = df.duplicated(
        subset=kc62_key,
        keep=False
    ).sum()

    print(name, duplicate_count)

cancers 0
diagnostic 0
uptake 0
referral 0

In [39]:
kc63_key = [
    "collectionyearrange",
    "parent_orgonscode",
    "parent_org_name",
    "org_name",
    "org_type",
    "age_band"
]

duplicate_count = coverage.duplicated(
    subset=kc63_key,
    keep=False
).sum()

print("coverage", duplicate_count)

coverage 0

In [40]:
kc63_key2 = [
    "collectionyearrange",
    "parent_orgonscode",
    "parent_org_name",
    "org_onscode",
    "org_name",
    "org_type",
    "age_band"
]

duplicate_count = coverage.duplicated(
    subset=kc63_key,
    keep=False
).sum()

print("coverage", duplicate_count)

coverage 0

**Adding org code to KC62**

In [42]:
org_lookup = coverage[
    ["org_onscode",
     "parent_orgonscode",
     "org_name",
     "org_type"]
].drop_duplicates()

org_lookup.groupby(
    ["org_name","org_type"]
)["org_onscode"].nunique().sort_values(ascending=False)

org_name                  org_type
Buckinghamshire           LA          2
North Yorkshire           LA          2
Dorset                    LA          2
Somerset                  LA          2
SALFORD                   LA          1
                                     ..
HOUNSLOW                  LA          1
HILLINGDON                LA          1
HERTFORDSHIRE             LA          1
HEREFORDSHIRE, COUNTY OF  LA          1
Harrow                    LA          1
Name: org_onscode, Length: 318, dtype: int64

In [44]:
coverage.loc[
    coverage["org_name"].isin([
        "Buckinghamshire",
        "Dorset",
        "North Yorkshire",
        "Somerset"
    ]),
    [
        "collectionyearrange",
        "parent_orgonscode",
        "org_onscode",
        "org_name",
        "org_type"
    ]
].drop_duplicates().sort_values(
    ["org_name", "collectionyearrange"]
)

,collectionyearrange,parent_orgonscode,org_onscode,org_name,org_type
498,2015-16,E12000008,E10000002,Buckinghamshire,LA
647,2016-17,E12000008,E10000002,Buckinghamshire,LA
797,2017-18,E12000008,E10000002,Buckinghamshire,LA
947,2018-19,E12000008,E10000002,Buckinghamshire,LA
1097,2019-20,E12000008,E10000002,Buckinghamshire,LA
1246,2020-21,E12000008,E06000060,Buckinghamshire,LA
1395,2021-22,E12000008,E06000060,Buckinghamshire,LA
1545,2022-23,E12000008,E06000060,Buckinghamshire,LA
1676,2023-24,E12000008,E06000060,Buckinghamshire,LA
1852,2024-25,E12000008,E06000060,Buckinghamshire,LA
517,2015-16,E12000009,E10000009,Dorset,LA
667,2016-17,E12000009,E10000009,Dorset,LA
817,2017-18,E12000009,E10000009,Dorset,LA
967,2018-19,E12000009,E10000009,Dorset,LA
1115,2019-20,E12000009,E06000059,Dorset,LA
1264,2020-21,E12000009,E06000059,Dorset,LA
1413,2021-22,E12000009,E06000059,Dorset,LA
1563,2022-23,E12000009,E06000059,Dorset,LA
1694,2023-24,E12000009,E06000059,Dorset,LA
1870,2024-25,E12000009,E06000059,Dorset,LA
419,2015-16,E12000003,E10000023,North Yorkshire,LA
569,2016-17,E12000003,E10000023,North Yorkshire,LA
719,2017-18,E12000003,E10000023,North Yorkshire,LA
869,2018-19,E12000003,E10000023,North Yorkshire,LA
1019,2019-20,E12000003,E10000023,North Yorkshire,LA
1168,2020-21,E12000003,E10000023,North Yorkshire,LA
1317,2021-22,E12000003,E10000023,North Yorkshire,LA
1466,2022-23,E12000003,E10000023,North Yorkshire,LA
1588,2023-24,E12000003,E06000065,North Yorkshire,BSU
1699,2023-24,E12000003,E06000065,North Yorkshire,LA
1764,2024-25,E12000003,E06000065,North Yorkshire,BSU
1875,2024-25,E12000003,E06000065,North Yorkshire,LA
519,2015-16,E12000009,E10000027,Somerset,LA
669,2016-17,E12000009,E10000027,Somerset,LA
819,2017-18,E12000009,E10000027,Somerset,LA
969,2018-19,E12000009,E10000027,Somerset,LA
1118,2019-20,E12000009,E10000027,Somerset,LA
1267,2020-21,E12000009,E10000027,Somerset,LA
1416,2021-22,E12000009,E10000027,Somerset,LA
1566,2022-23,E12000009,E10000027,Somerset,LA
1695,2023-24,E12000009,E06000066,Somerset,BSU
1702,2023-24,E12000009,E06000066,Somerset,LA
1871,2024-25,E12000009,E06000066,Somerset,BSU
1878,2024-25,E12000009,E06000066,Somerset,LA

**Validating that kc62_key is unique**

In [45]:
for name, df in {
    "uptake": uptake,
    "cancers": cancers,
    "diagnostic": diagnostic,
    "referral": referral
}.items():

    dupes = df.duplicated(
        subset=kc62_key
    ).sum()

    print(name, dupes)

uptake 0
cancers 0
diagnostic 0
referral 0

**Merge**

In [46]:
master = uptake.merge(
    cancers,
    on=kc62_key,
    how="left"
)

master = master.merge(
    diagnostic,
    on=kc62_key,
    how="left"
)

master = master.merge(
    referral,
    on=kc62_key,
    how="left"
)

In [47]:
len(uptake)
len(master)

8593

In [48]:
master.head()

,collectionyearrange,parent_org_code,parent_org_name,org_name,org_type,age_band,table_code,screened,invited,uptake,...,rate_small_invasive_y,rate_small_invasive_warning,sdr,sdr_warning,initial_referred,percent_assessment,referral_cyt_bio,open_biop_total,final_str,percent_str
0,2014-15,E92000001,England,England,National,45-49,A,159030.0,238589.0,66.65437216300836,...,NaN,NaN,NaN,NaN,12212.0,7.679054266490599,5191.0,302.0,122.0,0.07671508520404956
1,2014-15,E92000001,England,England,National,45-49,A and C1,170563.0,252740.0,67.48555828123763,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014-15,E92000001,England,England,National,45-49,A to C2,172930.0,259507.0,66.63789416085115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2014-15,E92000001,England,England,National,45-49,A to D,173032.0,259609.0,66.6510020839031,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2014-15,E92000001,England,England,National,45-49,B,1971.0,6151.0,32.04357015119493,...,NaN,NaN,NaN,NaN,167.0,8.472856418061896,80.0,2.0,3.0,0.15220700152207

**ONS Lookup table**

In [50]:
ons_lookup = coverage[
    [
        "collectionyearrange",
        "org_name",
        "org_onscode"
    ]
].drop_duplicates()

In [51]:
ons_lookup[
    ons_lookup["org_name"].isin([
        "Buckinghamshire",
        "Dorset",
        "North Yorkshire",
        "Somerset"
    ])
].sort_values(
    ["org_name","collectionyearrange"]
)

     collectionyearrange         org_name org_onscode
498              2015-16  Buckinghamshire   E10000002
647              2016-17  Buckinghamshire   E10000002
797              2017-18  Buckinghamshire   E10000002
947              2018-19  Buckinghamshire   E10000002
1097             2019-20  Buckinghamshire   E10000002
1246             2020-21  Buckinghamshire   E06000060
1395             2021-22  Buckinghamshire   E06000060
1545             2022-23  Buckinghamshire   E06000060
1676             2023-24  Buckinghamshire   E06000060
1852             2024-25  Buckinghamshire   E06000060
517              2015-16           Dorset   E10000009
667              2016-17           Dorset   E10000009
817              2017-18           Dorset   E10000009
967              2018-19           Dorset   E10000009
1115             2019-20           Dorset   E06000059
1264             2020-21           Dorset   E06000059
1413             2021-22           Dorset   E06000059
1563             2022-23           Dorset   E06000059
1694             2023-24           Dorset   E06000059
1870             2024-25           Dorset   E06000059
419              2015-16  North Yorkshire   E10000023
569              2016-17  North Yorkshire   E10000023
719              2017-18  North Yorkshire   E10000023
869              2018-19  North Yorkshire   E10000023
1019             2019-20  North Yorkshire   E10000023
1168             2020-21  North Yorkshire   E10000023
1317             2021-22  North Yorkshire   E10000023
1466             2022-23  North Yorkshire   E10000023
1588             2023-24  North Yorkshire   E06000065
1764             2024-25  North Yorkshire   E06000065
519              2015-16         Somerset   E10000027
669              2016-17         Somerset   E10000027
819              2017-18         Somerset   E10000027
969              2018-19         Somerset   E10000027
1118             2019-20         Somerset   E10000027
1267             2020-21         Somerset   E10000027
1416             2021-22         Somerset   E10000027
1566             2022-23         Somerset   E10000027
1695             2023-24         Somerset   E06000066
1871             2024-25         Somerset   E06000066

In [54]:
check = (
    ons_lookup
    .groupby(
        ["collectionyearrange","org_name"]
    )["org_onscode"]
    .nunique()
)

check.sort_values(
    ascending=False
).head(20)

collectionyearrange  org_name
2024-25              Yorkshire and The Humber        1
2014-15              BARKING AND DAGENHAM            1
                     BARNET                          1
                     BARNSLEY                        1
                     BATH AND NORTH EAST SOMERSET    1
                     BEDFORD                         1
                     BEXLEY                          1
                     BIRMINGHAM                      1
                     BLACKBURN WITH DARWEN           1
                     BLACKPOOL                       1
                     BOLTON                          1
                     BOURNEMOUTH                     1
                     BRACKNELL FOREST                1
                     BRADFORD                        1
                     BRENT                           1
2024-25              Warrington                      1
                     Wandsworth                      1
                     Waltham Forest                  1
                     Walsall                         1
                     Wakefield                       1
Name: org_onscode, dtype: int64

**Merge ONS**

In [55]:
master = master.merge(
    ons_lookup,
    on=[
        "collectionyearrange",
        "org_name"
    ],
    how="left"
)

In [56]:
master.head()

,collectionyearrange,parent_org_code,parent_org_name,org_name,org_type,age_band,table_code,screened,invited,uptake,...,rate_small_invasive_warning,sdr,sdr_warning,initial_referred,percent_assessment,referral_cyt_bio,open_biop_total,final_str,percent_str,org_onscode
0,2014-15,E92000001,England,England,National,45-49,A,159030.0,238589.0,66.65437216300836,...,NaN,NaN,NaN,12212.0,7.679054266490599,5191.0,302.0,122.0,0.07671508520404956,E92000001
1,2014-15,E92000001,England,England,National,45-49,A and C1,170563.0,252740.0,67.48555828123763,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E92000001
2,2014-15,E92000001,England,England,National,45-49,A to C2,172930.0,259507.0,66.63789416085115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E92000001
3,2014-15,E92000001,England,England,National,45-49,A to D,173032.0,259609.0,66.6510020839031,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E92000001
4,2014-15,E92000001,England,England,National,45-49,B,1971.0,6151.0,32.04357015119493,...,NaN,NaN,NaN,167.0,8.472856418061896,80.0,2.0,3.0,0.15220700152207,E92000001

**CHECK THIS WITH WILL**

In [57]:
master["org_onscode"].isna().sum()

np.int64(5112)

In [58]:
master.loc[
    master["org_onscode"].isna(),
    ["collectionyearrange","org_name"]
].drop_duplicates()

     collectionyearrange                  org_name
1089             2014-15  North East and Yorkshire
1091             2014-15                  Midlands
1145             2015-16  North East and Yorkshire
1147             2015-16                  Midlands
1201             2016-17  North East and Yorkshire
...                  ...                       ...
8044             2024-25                  Worthing
8045             2024-25                      Avon
8049             2024-25        North & East Devon
8051             2024-25               South Devon
8052             2024-25                West Devon

[639 rows x 2 columns]

In [59]:
master_key = [
    "collectionyearrange",
    "org_onscode",
    "age_band",
    "table_code"
]

In [60]:
ons_lookup.groupby(
    ["collectionyearrange","org_name"]
)["org_onscode"].nunique().max()

1

In [61]:
master.head()

,collectionyearrange,parent_org_code,parent_org_name,org_name,org_type,age_band,table_code,screened,invited,uptake,...,rate_small_invasive_warning,sdr,sdr_warning,initial_referred,percent_assessment,referral_cyt_bio,open_biop_total,final_str,percent_str,org_onscode
0,2014-15,E92000001,England,England,National,45-49,A,159030.0,238589.0,66.65437216300836,...,NaN,NaN,NaN,12212.0,7.679054266490599,5191.0,302.0,122.0,0.07671508520404956,E92000001
1,2014-15,E92000001,England,England,National,45-49,A and C1,170563.0,252740.0,67.48555828123763,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E92000001
2,2014-15,E92000001,England,England,National,45-49,A to C2,172930.0,259507.0,66.63789416085115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E92000001
3,2014-15,E92000001,England,England,National,45-49,A to D,173032.0,259609.0,66.6510020839031,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E92000001
4,2014-15,E92000001,England,England,National,45-49,B,1971.0,6151.0,32.04357015119493,...,NaN,NaN,NaN,167.0,8.472856418061896,80.0,2.0,3.0,0.15220700152207,E92000001

In [62]:
master.to_csv(
    "master_kc62.csv",
    index=False
)

In [63]:
from google.colab import files

files.download("master_kc62.csv")

In [64]:
print(master.shape)

print(master["org_name"].nunique())

print(master["collectionyearrange"].nunique())

(8593, 44)
89
11